set_property SRC_FILE_INFO {cfile:/home/kmrocki/git/gb/verilog/pynq-z1.xdc rfile:../pynq-z1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin h16   iostandard lvcmos33 } [get_ports { clk }]; #io_l13p_t2_mrcc_35 sch=sysclk
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin m20   iostandard lvcmos33 } [get_ports { sw[0] }]; #io_l7n_t1_ad2n_35 sch=sw[0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin m19   iostandard lvcmos33 } [get_ports { sw[1] }]; #io_l7p_t1_ad2p_35 sch=sw[1]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin l15   iostandard lvcmos33 } [get_ports { led_rgb[0] }]; #io_l22n_t3_ad7n_35 sch=led4_b
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin g17   iostandard lvcmos33 } [get_ports { led_rgb[1] }]; #io_l16p_t2_35 sch=led4_g
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin n15   iostandard lvcmos33 } [get_ports { led_rgb[2] }]; #io_l21p_t3_dqs_ad14p_35 sch=led4_r
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin g14   iostandard lvcmos33 } [get_ports { led_rgb[3] }]; #io_0_35 sch=led5_b
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin l14   iostandard lvcmos33 } [get_ports { led_rgb[4] }]; #io_l22p_t3_ad7p_35 sch=led5_g
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin m15   iostandard lvcmos33 } [get_ports { led_rgb[5] }]; #io_l23n_t3_35 sch=led5_r
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin r14   iostandard lvcmos33 } [get_ports { led[0] }]; #io_l6n_t0_vref_34 sch=led[0]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin p14   iostandard lvcmos33 } [get_ports { led[1] }]; #io_l6p_t0_34 sch=led[1]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin n16   iostandard lvcmos33 } [get_ports { led[2] }]; #io_l21n_t3_dqs_ad14n_35 sch=led[2]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin m14   iostandard lvcmos33 } [get_ports { led[3] }]; #io_l23p_t3_35 sch=led[3]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin d19   iostandard lvcmos33 } [get_ports { btn[0] }]; #io_l4p_t0_35 sch=btn[0]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin d20   iostandard lvcmos33 } [get_ports { btn[1] }]; #io_l4n_t0_35 sch=btn[1]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin l20   iostandard lvcmos33 } [get_ports { btn[2] }]; #io_l9n_t1_dqs_ad3n_35 sch=btn[2]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin l19   iostandard lvcmos33 } [get_ports { btn[3] }]; #io_l9p_t1_dqs_ad3p_35 sch=btn[3]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin y18   iostandard LVTTL } [get_ports { ja[0] }]; #io_l17p_t2_34 sch=ja_p[1]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin y19   iostandard LVTTL } [get_ports { ja[1] }]; #io_l17n_t2_34 sch=ja_n[1]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin y16   iostandard LVTTL } [get_ports { ja[2] }]; #io_l7p_t1_34 sch=ja_p[2]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin y17   iostandard LVTTL } [get_ports { ja[3] }]; #io_l7n_t1_34 sch=ja_n[2]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin u18   iostandard LVTTL } [get_ports { ja[4] }]; #io_l12p_t1_mrcc_34 sch=ja_p[3]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin u19   iostandard LVTTL } [get_ports { ja[5] }]; #io_l12n_t1_mrcc_34 sch=ja_n[3]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin w18   iostandard LVTTL } [get_ports { ja[6] }]; #io_l22p_t3_34 sch=ja_p[4]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin w19   iostandard LVTTL } [get_ports { ja[7] }]; #io_l22n_t3_34 sch=ja_n[4]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin w14   iostandard LVTTL } [get_ports { jb[0] }]; #io_l8p_t1_34 sch=jb_p[1]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin y14   iostandard LVTTL } [get_ports { jb[2] }]; #io_l8n_t1_34 sch=jb_n[1]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin t11   iostandard LVTTL } [get_ports { jb[4] }]; #io_l1p_t0_34 sch=jb_p[2]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin t10   iostandard LVTTL } [get_ports { jb[6] }]; #io_l1n_t0_34 sch=jb_n[2]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin v16   iostandard LVTTL } [get_ports { jb[1] }]; #io_l18p_t2_34 sch=jb_p[3]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin w16   iostandard LVTTL } [get_ports { jb[3] }]; #io_l18n_t2_34 sch=jb_n[3]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin v12   iostandard LVTTL } [get_ports { jb[5] }]; #io_l4p_t0_34 sch=jb_p[4]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin w13   iostandard LVTTL } [get_ports { jb[7] }]; #io_l4n_t0_34 sch=jb_n[4]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin t14   iostandard lvcmos33 } [get_ports { ck_io[0] }]; #io_l5p_t0_34 sch=ck_io[0]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin u12   iostandard lvcmos33 } [get_ports { ck_io[1] }]; #io_l2n_t0_34 sch=ck_io[1]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin u13   iostandard lvcmos33 } [get_ports { ck_io[2] }]; #io_l3p_t0_dqs_pudc_b_34 sch=ck_io[2]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin v13   iostandard lvcmos33 } [get_ports { ck_io[3] }]; #io_l3n_t0_dqs_34 sch=ck_io[3]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin v15   iostandard lvcmos33 } [get_ports { ck_io[4] }]; #io_l10p_t1_34 sch=ck_io[4]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin t15   iostandard lvcmos33 } [get_ports { ck_io[5] }]; #io_l5n_t0_34 sch=ck_io[5]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin r16   iostandard lvcmos33 } [get_ports { ck_io[6] }]; #io_l19p_t3_34 sch=ck_io[6]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin u17   iostandard lvcmos33 } [get_ports { ck_io[7] }]; #io_l9n_t1_dqs_34 sch=ck_io[7]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin v17   iostandard lvcmos33 } [get_ports { ck_io[8] }]; #io_l21p_t3_dqs_34 sch=ck_io[8]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin v18   iostandard lvcmos33 } [get_ports { ck_io[9] }]; #io_l21n_t3_dqs_34 sch=ck_io[9]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin t16   iostandard lvcmos33 } [get_ports { ck_io[10] }]; #io_l9p_t1_dqs_34 sch=ck_io[10]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin r17   iostandard lvcmos33 } [get_ports { ck_io[11] }]; #io_l19n_t3_vref_34 sch=ck_io[11]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin p18   iostandard lvcmos33 } [get_ports { ck_io[12] }]; #io_l23n_t3_34 sch=ck_io[12]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin n17   iostandard lvcmos33 } [get_ports { ck_io[13] }]; #io_l23p_t3_34 sch=ck_io[13]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin l17   iostandard tmds_33  } [get_ports { clk_n }]; #io_l11n_t1_srcc_35 sch=hdmi_tx_clk_n
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin l16   iostandard tmds_33  } [get_ports { clk_p }]; #io_l11p_t1_srcc_35 sch=hdmi_tx_clk_p
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin k18   iostandard tmds_33  } [get_ports { data_n[0] }]; #io_l12n_t1_mrcc_35 sch=hdmi_tx_d_n[0]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin k17   iostandard tmds_33  } [get_ports { data_p[0] }]; #io_l12p_t1_mrcc_35 sch=hdmi_tx_d_p[0]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin j19   iostandard tmds_33  } [get_ports { data_n[1] }]; #io_l10n_t1_ad11n_35 sch=hdmi_tx_d_n[1]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin k19   iostandard tmds_33  } [get_ports { data_p[1] }]; #io_l10p_t1_ad11p_35 sch=hdmi_tx_d_p[1]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin h18   iostandard tmds_33  } [get_ports { data_n[2] }]; #io_l14n_t2_ad4n_srcc_35 sch=hdmi_tx_d_n[2]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { package_pin j18   iostandard tmds_33  } [get_ports { data_p[2] }]; #io_l14p_t2_ad4p_srcc_35 sch=hdmi_tx_d_p[2]
